- name: Install patches
  community.general.syspatch:
  become: true
  register: syspatch
  tags:
    - syspatch

- name: Print output from syspatch
  ansible.builtin.debug:
    msg: '{{ syspatch.stdout_lines }}'
  when: syspatch.stdout != ""
  tags:
    - syspatch_debug

- name: Reboot after patching
  ansible.builtin.reboot:
  become: true
  when: syspatch.reboot_needed
  tags:
    - syspatch_reboot
